version: '3'
services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: nginx_reverse_proxy
    depends_on:
      - flask
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:80

  flask:
    image: paz45/flask
    container_name: flask
    build:
      context: ./flask
    ports:
      - 80:80